Exception ignored in: <function BufferedFile.__del__ at 0x7f49ed954e50>
Traceback (most recent call last):
  File "/home/vvay001/.local/lib/python3.9/site-packages/paramiko/file.py", line 67, in __del__
  File "/home/vvay001/.local/lib/python3.9/site-packages/paramiko/channel.py", line 1390, in close
  File "/home/vvay001/.local/lib/python3.9/site-packages/paramiko/channel.py", line 989, in shutdown_write
  File "/home/vvay001/.local/lib/python3.9/site-packages/paramiko/channel.py", line 965, in shutdown
  File "/home/vvay001/.local/lib/python3.9/site-packages/paramiko/transport.py", line 1936, in _send_user_message
AttributeError: 'NoneType' object has no attribute 'time'
